<script>
  import logo from './assets/svelte.png'
  import Counter from './lib/Counter.svelte'
  import { Greet } from '../wailsjs/go/main/App';

  let name = "";
  let greeting = "";

  function greet() {
    Greet(name).then((result) => {
      greeting = result;
    });
  }
</script>

<main>
  <img src={logo} alt="Svelte Logo" />
  <h1>
    Hello world!
  </h1>

  <Counter />

  <p>
    Visit <a href="https://svelte.dev">svelte.dev</a> to learn how to build Svelte
    apps.
  </p>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme">SvelteKit</a> for
    the officially supported framework, also powered by Vite!
  </p>

  <hr>

  <p>This tests that the Go functionality is working too. The greeting is generated by Go.</p>
  <div id="input" class="mb-4" data-wails-no-drag>
    <label class="block text-sm font-bold mb-2" for="name">
      Name
    </label>
    <input id="name" type="text" bind:value={name} class="shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" on:click={greet}>Greetings</button>
  </div>
  {#if greeting}
    <div id="result">{greeting}</div>
  {/if}
</main>

<style>
  :root {
    font-family: 'Nunito', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      background-color: rgba(27, 38, 54, 1);
    text-align: center;
    color: white;
  }

  main {
    text-align: center;
    padding: 1em;
    margin: 0 auto;
    height: 100vh;
  }

  img {
    height: 16rem;
    width: 16rem;
  }

  h1 {
    @apply text-3xl font-bold underline text-emerald-700;
    /*color: #ff3e00;
    text-transform: uppercase;
    font-size: 4rem;
    font-weight: 100;*/
    line-height: 1.1;
    margin: 2rem auto;
    max-width: 14rem;
  }

  p {
    max-width: 14rem;
    margin: 1rem auto;
    line-height: 1.35;
  }

  
@font-face {
    font-family: "Nunito";
    font-style: normal;
    font-weight: 400;
    src: local(""),
    url("assets/fonts/nunito-v16-latin-regular.woff2") format("woff2");
}

  @media (min-width: 480px) {
    h1 {
      max-width: none;
    }

    p {
      max-width: none;
    }
  }
</style>
